name = "service"
main = "src/index.ts"
compatibility_date = "2024-10-25"

[triggers]
crons = []

[[d1_databases]]
binding = "DB"
database_name = "personaltcm"
database_id = "99f20991-68ed-41cd-9784-ca820b8260b7"
preview_database_id = "addeb323-a560-4621-910c-f60e73ecef82"

[ai]
binding = "AI"

[placement]
mode = "smart"

[[r2_buckets]]
binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'peronaltcm'
preview_bucket_name = 'test'
